<Project>
    <PropertyGroup>
        <Version>0.1.0</Version>
        <Authors>Moez REBAI</Authors>
        <Company>JoYa</Company>
        <RepositoryUrl>https://github.com/moezRebai/Streamly</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageTags>streaming;nats;finance;fx;realtime;distributed</PackageTags>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub"
                          Version="8.0.0" PrivateAssets="All"/>
    </ItemGroup>
</Project>