using System.Reactive.Subjects;
using Streamly.Core.Models;

namespace Streamly.Subscriber.Internal;

/// <summary>
/// Internal state for a single active subscription
/// Managed by SubscriptionManager
/// Client never sees this
/// </summary>
internal class SubscriptionState<TResponse>
{
    /// <summary>
    /// Correlation ID generated by library for handshake
    /// Temporary - used only until confirmation received
    /// </summary>
    public string CorrelationId { get; init; } = string.Empty;

    /// <summary>
    /// Real RequestId assigned by leader
    /// Populated after confirmation received
    /// Used for response filtering
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    /// Stream behavior for this subscription
    /// </summary>
    public StreamBehavior Behavior { get; init; }

    /// <summary>
    /// The subject that bridges Redis messages to IObservable
    /// OnNext called when response arrives for this RequestId
    /// OnError called on unrecoverable error
    /// OnCompleted called when stream closes
    /// </summary>
    public Subject<TResponse> Subject { get; } = new();

    /// <summary>
    /// Last known leadership epoch
    /// Used to reject stale messages
    /// </summary>
    public long LastKnownEpoch { get; set; }

    /// <summary>
    /// How many reconnect attempts have been made
    /// Reset to 0 on successful response
    /// </summary>
    public int ReconnectAttempts { get; set; }

    /// <summary>
    /// When subscription was created
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Whether this subscription is waiting for confirmation
    /// True from Subscribe call until ConfirmationMessage received
    /// </summary>
    public bool WaitingForConfirmation { get; set; } = true;

    /// <summary>
    /// Whether this subscription has been disposed by client
    /// </summary>
    public bool IsDisposed { get; set; }
}
