using System.Text.Json.Serialization;

namespace Streamly.Core.Models;

/// <summary>
/// Sent by leader to confirm a subscription request
/// Contains the real RequestId assigned by the leader
/// Client uses this to filter responses from streams.responses channel
/// </summary>
public class ConfirmationMessage
{
    /// <summary>
    /// Correlation ID generated by library internally
    /// Used to match confirmation back to the waiting subscription
    /// </summary>
    [JsonPropertyName("correlationId")]
    public string CorrelationId { get; set; } = string.Empty;

    /// <summary>
    /// Real RequestId assigned by leader (SHA256 hash)
    /// Single source of truth - leader owns this
    /// </summary>
    [JsonPropertyName("requestId")]
    public string RequestId { get; set; } = string.Empty;

    /// <summary>
    /// Stream name this confirmation belongs to
    /// </summary>
    [JsonPropertyName("streamName")]
    public string StreamName { get; set; } = string.Empty;

    /// <summary>
    /// Leadership epoch at time of confirmation
    /// </summary>
    [JsonPropertyName("epoch")]
    public long Epoch { get; set; }

    /// <summary>
    /// When confirmation was issued (UTC)
    /// </summary>
    [JsonPropertyName("confirmedAt")]
    public DateTime ConfirmedAt { get; set; }
}
