<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <OutputType>exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Streamly.FakePublisher</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <GarbageCollectionAdaptationMode>0</GarbageCollectionAdaptationMode>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Streamly.Audit\Streamly.Audit.csproj" />
        <ProjectReference Include="..\..\src\Streamly\Streamly.csproj" />
        <ProjectReference Include="..\..\src\Streamly.Monitoring\Streamly.Monitoring.csproj" />
    </ItemGroup>
</Project>
