using System.Text.Json.Serialization;

namespace Streamly.Core.Models;

/// <summary>
/// Wraps user request with stream behavior metadata
/// Published to Redis by subscriber library (client side)
///
/// Client never sees this - library creates it internally
///
/// Flow:
///   1. Client calls subscriber.Stream(request, Live)
///   2. Library creates RequestEnvelope internally
///   3. Library generates CorrelationId (GUID, hidden from client)
///   4. Library publishes envelope to streams.requests.{streamName}
///   5. Leader receives, computes RequestId, sends ConfirmationMessage
///   6. Library receives confirmation, starts routing responses
/// </summary>
public class RequestEnvelope<TRequest>
{
    /// <summary>
    /// User's request data
    /// </summary>
    [JsonPropertyName("request")]
    public TRequest Request { get; set; } = default!;

    /// <summary>
    /// Stream behavior (default: Live)
    /// Included in RequestId hash to differentiate
    /// Live vs Snapshot for same request payload
    /// </summary>
    [JsonPropertyName("behavior")]
    public StreamBehavior Behavior { get; set; } = StreamBehavior.Live;

    /// <summary>
    /// Internal correlation ID generated by library (GUID)
    /// Used for handshake: client identifies its subscription attempt
    /// Leader sends ConfirmationMessage back with same CorrelationId + real RequestId
    /// Client never sees or manages this
    /// </summary>
    [JsonPropertyName("correlationId")]
    public string CorrelationId { get; set; } = string.Empty;

    /// <summary>
    /// When subscription was initiated (UTC)
    /// </summary>
    [JsonPropertyName("subscribedAt")]
    public DateTime SubscribedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// InstanceId of the subscribing service.
    /// Used by publisher to track per-subscriber leases.
    /// </summary>
    [JsonPropertyName("subscriberId")]
    public string SubscriberId { get; set; } = string.Empty;
}